Repository perwendel/spark, pull requests merged in 2020-09, with the labels that each got.

#1071 Expose get/set on Service.embeddedServerIdentifier
  src/main/java/spark/Service.java
  src/test/java/spark/ServiceTest.java
Labels: Feature request

#1192 Fix for broken travis build
  .travis.yml
Labels: bug-fix

#964 Add methods to set long and date headers
  src/main/java/spark/Response.java
  src/test/java/spark/ResponseTest.java
Labels: Feature request

#1100 Get all mapped routes
  src/main/java/spark/Service.java
  src/main/java/spark/Spark.java
  src/main/java/spark/route/Routes.java
  src/main/java/spark/routematch/RouteMatch.java
  src/test/java/spark/MultipleServicesTest.java
  src/test/java/spark/RequestTest.java
Labels: Feature request, Major 3.0 candidate
